const actionTypes = {
    GET_WEATHER: 'GET_WEATHER',
    SET_DAILY_WEATHER: 'SET_DAILY_WEATHER',
    SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER',
    SET_MOVIES: 'SET_MOVIES',
    GET_MOVIES: 'GET_MOVIES',
    SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
}
export default actionTypes;